parameters:
    ticketpark.role_hierarchy.class:                Ticketpark\DynamicRoleBundle\Security\RoleHierarchy
    ticketpark.role.provider.class:                 Ticketpark\DynamicRoleBundle\Security\RoleProvider
    ticketpark.role.dbal.schema.class:              Ticketpark\DynamicRoleBundle\Security\Dbal\Schema
    ticketpark.role.dbal.schema_listener.class:     Ticketpark\DynamicRoleBundle\EventListener\RoleSchemaListener
    ticketpark.role_table.name:                     ~

services:
    security.role_hierarchy:
        class: %ticketpark.role_hierarchy.class%
        arguments:
            - { role_table_name: %ticketpark.role_table.name% }
            - %security.role_hierarchy.roles%
            - @ticketpark.role_table.connection
            - "@ticketpark.dynamic_role_cache"

    ticketpark.role.provider:
        class: %ticketpark.role.provider.class%
        arguments:
            - { role_table_name: %ticketpark.role_table.name% }
            - @ticketpark.role_table.connection
            - "@ticketpark.dynamic_role_cache"

    ticketpark.role.dbal.schema:
        class: %ticketpark.role.dbal.schema.class%
        arguments:
            - { role_table_name: %ticketpark.role_table.name% }
            - @ticketpark.role_table.connection

    ticketpark.role.dbal.schema_listener:
        class: %ticketpark.role.dbal.schema_listener.class%
        arguments:
            - @service_container

    ticketpark.dynamic_role_cache:
        class: Doctrine\Common\Cache\VoidCache
        public: false
